## Основы линейной алгебры

In [34]:
import numpy as np
import random as round
import scipy.linalg as lp

In [35]:
base_list1 = [1, 2, 3, 4]
base_list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
base_list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [36]:
def f1(x):
    return x + 2


#projection = list(map(np.sin , base_list1))
projection = list(map(lambda x:  x*x, base_list1))

#for x in projection:
  #  print(x)
projection

[1, 4, 9, 16]

In [37]:
base_list3 = [42] * 5
base_list4 = [[1, 2, 3]] * 3
base_list4

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [38]:
base_list4[0][1] = 0
base_list4

[[1, 0, 3], [1, 0, 3], [1, 0, 3]]

In [39]:
XX = np.array([1, 2, 3]) # два икса это вектор (большие или маленькие)
yy = np.array(base_list2)
zz = np.array(yy)
aa = np.arange(1, 10, 2)
bb = np.linspace(1, 10, 8)
bb

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

## Алгебра матриц

## Умножение матрицы на вектор

In [40]:
def Matrix2Vector(A, a):
    n, m = np.shape(A)
    # A= np.array(A)

    b = [0]*n
    for i in range(0, n): # для всех строк матрицы рассчитываем ячейки вектора реультата
        s = 0
        for j in range(0, m): # j это номер элемента в строке
            s += A[i, j] * a[j]
        b[i] = s
    return b

A = np.array(base_list2)
b1 = Matrix2Vector(A, [1, 2, 3])
b1



[14, 32, 50]

### Транспонирование матрицы

In [41]:
def Transpose(A):
    n, m = np.shape(A)
    B = []
    for j in range(0, m): # перебираем номера столбцов матрицы А
        b = []
        for i in range(0, n): # перебираем каждый элмент столбца А
            b.append(A[i, j])
        B.append(b)
    return np.array(B)

B = Transpose(A)
C = A.T
D = A.transpose()
D


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Простейшие операции

In [42]:
C = A * B
D = A @ B
D

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [43]:
D = np.dot(A, B)
C = np.cross(A, B)
D, C

(array([[ 14,  32,  50],
        [ 32,  77, 122],
        [ 50, 122, 194]]),
 array([[  2,  -4,   2],
        [ 10, -20,  10],
        [ 18, -36,  18]]))

### Умножение матрицы на матрицу

In [46]:
def Matrix2Vector(A, B):
    la = np.shape(A)
    lb = np.shape(B)

    # la[1] == lb[2]
    C = []
    for i in range(0, lb[1]):
        C.append([0] * la[0])

    for i in range(0, la[0]):
        for j in range(0, lb[1]):
            s = 0
            for k in range(0, la[1]): # k - номер ячейки строки А и номер ячейки столбца В
                s += A[i, k] * B[k, j]
            C[i][j] = s

    return np.array(C)

C = Matrix2Vector(A, A.T)
C

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [ ]:
def Triangle(A):
    M = np.array(A)
    n, m = np.shape(M)

    d = 1
    rank = min(n, m)